from __future__ import annotations

from dataclasses import asdict, dataclass

import yaml

from smsl_generation.support.client import SUPPORTED_PROVIDERS

from smsl_generation.support.scenarios import supported_scenarios


@dataclass(frozen=True)
class GenerationConfig:
    scenario: str = "hanoi"
    mode: str = "direct"
    model: str = "gpt-4o"
    provider: str = "auto"
    temperature: float = 0.0
    verbose: bool = True
    artifact_dir: str = ""
    out_json: str = ""
    execute_phase_scripts: bool = False
    validation_retries: int = 5
    style: str = "detailed"


def load_generation_config(path: str) -> GenerationConfig:
    with open(path, "r", encoding="utf-8") as fh:
        loaded = yaml.safe_load(fh) or {}
    if not isinstance(loaded, dict):
        raise ValueError("Generation config must be a YAML mapping.")
    config = GenerationConfig(**loaded)
    validate_generation_config(config)
    return config


def validate_generation_config(config: GenerationConfig) -> None:
    if config.scenario not in supported_scenarios():
        raise ValueError(
            "`scenario` must be one of: {}".format(", ".join(supported_scenarios()))
        )
    if config.mode not in {"direct", "indirect"}:
        raise ValueError("`mode` must be either `direct` or `indirect`.")
    if config.provider not in SUPPORTED_PROVIDERS:
        raise ValueError(
            "`provider` must be one of: {}".format(", ".join(sorted(SUPPORTED_PROVIDERS)))
        )
    if config.mode == "indirect" and not config.execute_phase_scripts:
        raise ValueError(
            "`execute_phase_scripts` must be true in `indirect` mode because the final JSON is generated by executing the returned phase scripts."
        )
    if config.validation_retries < 0:
        raise ValueError("`validation_retries` must be zero or greater.")


def render_generation_config(config: GenerationConfig) -> str:
    return yaml.safe_dump(asdict(config), sort_keys=False)
