from __future__ import annotations

import argparse
import json
from itertools import product


NUM_FACTS = 0
NUM_STATES = 0
INITIAL_STATE = "State_REPLACE_ME"
ITEMS = ()
POSITION_CODES = ()
# Fill the constants above with real scenario values.
# Keep the data types consistent across the whole file.
# If state names encode item identifiers as strings, ITEMS should usually be strings too.
# INITIAL_STATE must be the true puzzle start state, not just any valid state.
# NUM_STATES should be the actual number of phase-1 states generated by iter_state_codes().


def base_position_codes():
    # Return the symbols used for the raw Cartesian product in phase 1.
    # In simple encodings this can return POSITION_CODES directly.
    # If POSITION_CODES contain richer symbols than the raw product should use,
    # normalize them here.
    # Do not pre-filter illegal combinations here. Phase 1 only enumerates.
    raise NotImplementedError


def expand_state_codes(state_code):
    # Given one tuple from the Cartesian product, yield one or more concrete state codes.
    # Most scenarios should simply `yield tuple(state_code)`.
    # Use this only to expand one raw tuple into multiple symbolic encodings.
    # Do not remove impossible states here. That belongs to phase 2.
    raise NotImplementedError


def iter_state_codes():
    # Enumerate the over-complete symbolic state space for phase 1.
    # This phase only enumerates; do not filter states here.
    for state_code in product(base_position_codes(), repeat=len(ITEMS)):
        yield from expand_state_codes(state_code)


def encode_state(state_code):
    # Convert one structured symbolic state code into the phase-state string `State_...`.
    # Keep the fact order consistent with ITEMS.
    # The returned name must match the phase-state syntax expected by validation.
    raise NotImplementedError


def build_candidate_operations():
    # Enumerate every candidate symbolic operation that can appear under each state.
    # This phase builds one shared over-complete operation inventory, not per-state filtering.
    # Use symbolic names only, such as `Op_...`.
    # Do not inspect state legality here. Phase 3 will filter operations later.
    raise NotImplementedError


def parse_operation(operation_name):
    # Parse one symbolic phase operation into a structured operation code.
    # This parser must exactly match the format emitted by build_candidate_operations().
    # Return only the fields needed by target_state_for_operation(...).
    # Match the parser to the actual operation syntax for this scenario.
    # If the format is delimited, such as `Op_star_B`, prefer `split("_", 2)`.
    # If the format is compact, such as `Op_1a`, parse the suffix after `Op_` by position.
    raise NotImplementedError


def target_state_for_operation(state_code, operation_name):
    # Compute the candidate symbolic target state for this operation.
    # Usually this means: parse the operation, copy the state, update only the affected facts,
    # and encode the result.
    # Phase 1 only builds the over-complete graph, so do not reject no-op or illegal moves here.
    # Phase 3 and phase 4 are responsible for filtering bad transitions.
    raise NotImplementedError


def main():
    # Read no prior phase, enumerate the raw symbolic state space,
    # and write `phase_1.json`.
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="phase_1.json")
    args = parser.parse_args()

    operations = build_candidate_operations()
    sb = {
        "HEADER": {
            "INITIAL": INITIAL_STATE,
            "NUM_FACTS": NUM_FACTS,
            "NUM_STATES": NUM_STATES,
            "SUB_SBS": [],
        }
    }

    for state_code in iter_state_codes():
        state_name = encode_state(state_code)
        sb[state_name] = {
            operation_name: target_state_for_operation(state_code, operation_name)
            for operation_name in operations
        }

    with open(args.output, "w", encoding="utf-8") as fh:
        json.dump({"SB1": sb}, fh, indent=2)


if __name__ == "__main__":
    main()
